services:
  - type: web
    name: inquestofknowledge-website
    env: node
    plan: free
    buildCommand: rm -rf node_modules package-lock.json && npm install --no-optional --force && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
